packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  msgpackr-extract: set this to true or false
minimumReleaseAgeExclude:
  - expo-constants@57.0.8
  - '@expo/cli@57.0.11'
  - '@expo/inline-modules@0.1.4'
  - '@expo/local-build-cache-provider@57.0.5'
  - '@expo/log-box@57.0.2'
  - '@expo/prebuild-config@57.0.10'
  - babel-preset-expo@57.0.5
  - expo-asset@57.0.8
  - expo-modules-core@57.0.8
  - expo@57.0.9
